export const COUNTRY_NAME: {[key: string]: string} = {
    "US": "United States",
    "CA": "Canada",
    "GB": "United Kingdom",
    "AU": "Australia",
    "DE": "Germany",
    "FR": "France",
    "JP": "Japan",
    "CN": "China",
    "KR": "South Korea",
    "BR": "Brazil",
    "IN": "India",
    "RU": "Russia",
    "MX": "Mexico",
    "IT": "Italy",
    "ES": "Spain",
    "NL": "Netherlands",
    "SE": "Sweden",
    "CH": "Switzerland",
    "AR": "Argentina",
    "ZA": "South Africa",
    "NZ": "New Zealand",
    "NO": "Norway",
    "BE": "Belgium",
    "DK": "Denmark",
    "FI": "Finland",
    "AT": "Austria",
    "IE": "Ireland",
    "SG": "Singapore",
    "TR": "Turkey",
    "MY": "Malaysia",
    "TH": "Thailand",
    "ID": "Indonesia",
    "PH": "Philippines",
    "VN": "Việt Nam",
    "AE": "United Arab Emirates",
    "SA": "Saudi Arabia",
    "IL": "Israel",
    "EG": "Egypt",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "NG": "Nigeria",
    "KE": "Kenya",
    "CO": "Colombia",
    "CL": "Chile",
    "PL": "Poland",
    "PT": "Portugal",
    "CZ": "Czech Republic",
    "GR": "Greece",
    "HU": "Hungary",
    "RO": "Romania",
    "UA": "Ukraine",
    "VE": "Venezuela"
  };