function convertWeatherIcon (description = "broken clouds", icon = "04d") {
    const stateWeather = description + icon;

    const checkIcon = objWeatherIcon?.[stateWeather];

    // Trả về icon nếu tìm thấy, nếu không trả về giá trị mặc định
    return checkIcon ? `/icons/${checkIcon}` : "/icons/cloud.png"
}

const objWeatherIcon: {[key: string]: string} = {
    // day
    "light rain10d": "cloudRainSun.png",
    "moderate rain10d": "cloudManyRain.png",
    "heavy intensity rain10d": "showersRainSun.png",
    "very heavy rain10d": "showersRain.png",
    "extreme rain10d": "showersRain.png",
    "freezing rain13d": "cloudManySnow.png",
    "light intensity shower rain09d": "cloudyRainSun.png",
    "shower rain09d": "showersRain.png",
    "heavy intensity shower rain09d": "showersRain.png",
    "ragged shower rain09d": "cloudyRainSun.png",
    "light snow13d": "snow.png",
    "snow13d": "snow.png",
    "heavy snow13d": "manySnow.png",
    "sleet13d": "cloudSnowSun.png",
    "light shower sleet13d": "cloudSnowSun.png",
    "shower sleet13d": "cloudManySnow.png",
    "light rain and snow13d": "cloudSnowSun.png",
    "rain and snow13d": "cloudManySnow.png",
    "light shower snow13d": "cloudManySnowSun.png",
    "shower snow13d": "cloudSnow.png",
    "heavy shower snow13d": "cloudManySnow.png",
    "mist50d": "smallWind.png",
    "smoke50d": "smallWind.png",
    "haze50d": "smallWind.png",
    "sand/dust whirls50d": "tonado.png",
    "fog50d": "smallWind.png",
    "sand50d": "smallWind.png",
    "dust50d": "smallWind.png",
    "volcanic ash50d": "smallWind.png",
    "squalls50d": "windThunder.png",
    "tornado50d": "tonadothunder.png",
    "clear sky01d": "sun.png",
    "few clouds02d": "cloudSun.png",
    "scattered clouds03d": "cloudSmallWindSun.png",
    "broken clouds04d": "cloud.png",
    "overcast clouds04d": "cloudSmallWind.png",
    "thunderstorm with light rain11d": "thunderRainSun.png",
    "thunderstorm with rain11d": "thunderRain.png",
    "thunderstorm with heavy rain11d": "heavyThunderRain.png",
    "light thunderstorm11d": "cloudThunderSun.png",
    "thunderstorm11d": "thunder.png",
    "heavy thunderstorm11d": "thunder.png",
    "ragged thunderstorm11d": "cloudThunderSun.png",
    "thunderstorm with light drizzle11d": "thunderRainSun.png",
    "thunderstorm with drizzle11d": "thunderRain.png",
    "thunderstorm with heavy drizzle11d": "heavyThunderRain",
    "light intensity drizzle09d": "cloudyRainSun.png",
    "drizzle09d": "cloudyRain.png",
    "heavy intensity drizzle09d": "showersRain.png",
    "light intensity drizzle rain09d": "cloudyRainSun.png",
    "drizzle rain09d": "cloudyRain.png",
    "heavy intensity drizzle rain09d": "showersRain.png",
    "shower rain and drizzle09d": "cloudManyRain.png",
    "heavy shower rain and drizzle09d": "showersRain.png",
    "shower drizzle09d": "cloudManyRain.png",
    // night
    "light rain10n": "cloudRainMoon.png",
    "moderate rain10n": "cloudManyRain.png",
    "heavy intensity rain10n": "showersRainMoon.png",
    "very heavy rain10n": "showersRain.png",
    "extreme rain10n": "showersRain.png",
    "freezing rain13n": "cloudManySnow.png",
    "light intensity shower rain09n": "cloudyRainMoon.png",
    "shower rain09n": "showersRain.png",
    "heavy intensity shower rain09n": "showersRain.png",
    "ragged shower rain09n": "cloudyRainMoon.png",
    "light snow13n": "snow.png",
    "snow13n": "snow.png",
    "heavy snow13n": "manySnow.png",
    "sleet13n": "cloudSnowMoon.png",
    "light shower sleet13n": "cloudSnowMoon.png",
    "shower sleet13n": "cloudManySnow.png",
    "light rain and snow13n": "cloudSnowMoon.png",
    "rain and snow13n": "cloudManySnow.png",
    "light shower snow13n": "cloudManySnowMoon.png",
    "shower snow13n": "cloudSnow.png",
    "heavy shower snow13n": "cloudManySnow.png",
    "mist50n": "smallWind.png",
    "smoke50n": "smallWind.png",
    "haze50n": "smallWind.png",
    "sand/dust whirls50n": "tonado.png",
    "fog50n": "smallWind.png",
    "sand50n": "smallWind.png",
    "dust50n": "smallWind.png",
    "volcanic ash50n": "smallWind.png",
    "squalls50n": "windThunder.png",
    "tornado50n": "tonadothunder.png",
    "clear sky01n": "moon.png",
    "few clouds02n": "cloudMoon.png",
    "scattered clouds03n": "cloudSmallWindMoon.png",
    "broken clouds04n": "cloud.png",
    "overcast clouds04n": "cloudSmallWind.png",
    "thunderstorm with light rain11n": "thunderRainMoon.png",
    "thunderstorm with rain11n": "thunderRain.png",
    "thunderstorm with heavy rain11n": "heavyThunderRain.png",
    "light thunderstorm11n": "cloudThunderMoon.png",
    "thunderstorm11n": "thunder.png",
    "heavy thunderstorm11n": "thunder.png",
    "ragged thunderstorm11n": "cloudThunderMoon.png",
    "thunderstorm with light drizzle11n": "thunderRainMoon.png",
    "thunderstorm with drizzle11n": "thunderRain.png",
    "thunderstorm with heavy drizzle11n": "heavyThunderRain",
    "light intensity drizzle09n": "cloudyRainMoon.png",
    "drizzle09n": "cloudyRain.png",
    "heavy intensity drizzle09n": "showersRain.png",
    "light intensity drizzle rain09n": "cloudyRainMoon.png",
    "drizzle rain09n": "cloudyRain.png",
    "heavy intensity drizzle rain09n": "showersRain.png",
    "shower rain and drizzle09n": "cloudManyRain.png",
    "heavy shower rain and drizzle09n": "showersRain.png",
    "shower drizzle09n": "cloudManyRain.png",
}

export default convertWeatherIcon;
